#!/bin/sh

echo "003-fix-mysql: Fix MySQL Table"

echo "Drop Table and Update"

if echo "DESCRIBE think.item" |mysql --user="root" --password="Passw0rd!" --database="think" | grep "char(2000)"
then
    echo "Table Fix already applied."
else
    mysql --user="root" --password="Passw0rd!" --database="think" < ~/.pot/core/env-setup/system-scripts/mysql-db-script.txt
fi
exit $?


