#!/bin/sh

echo "008-fset-forever-scripts"

if [ -e "/etc/init/forever-shipping.conf" ]
then
  echo Passw0rd! | sudo -S rm /etc/init/forever-shipping.conf
fi

echo Passw0rd! | sudo -S cp ~/.pot/core/env-setup/system-scripts/forever-pot-* /etc/init
echo Passw0rd! | sudo -S chmod 644 /etc/init/forever-pot-*
exit $?