swagger: '2.0'
info:
  x-ibm-name: logistics
  title: logistics
  version: 1.0.0
schemes:
  - https
basePath: /logistics
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientID:
    description: ''
    in: header
    name: X-IBM-Client-Id
    type: apiKey
security:
  - clientID: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  gateway: datapower-gateway
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
  properties:
    shipping_svc_url:
      value: 'http://shipping.think.ibm:5000/calculate'
      description: Location of the shipping calculator service
      encoded: false
  assembly:
    execute:
      - activity-log:
          title: activity-log
          content: payload
          error-content: payload
      - operation-switch:
          title: operation-switch
          case:
            - operations:
                - shipping.calc
              execute:
                - invoke:
                    title: invoke_xyz
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    target-url: '$(shipping_svc_url)?company=xyz&from_zip=90210&to_zip={zip}'
                    output: xyz_response
                - invoke:
                    title: invoke_cek
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    target-url: '$(shipping_svc_url)?company=cek&from_zip=90210&to_zip={zip}'
                    output: cek_response
                - map:
                    title: map_responses
                    inputs:
                      xyz:
                        schema:
                          $schema: 'http://json-schema.org/draft-04/schema#'
                          id: 'http://jsonschema.net'
                          type: object
                          properties:
                            company:
                              id: 'http://jsonschema.net/company'
                              type: string
                              name: company
                            rates:
                              id: 'http://jsonschema.net/rates'
                              type: object
                              properties:
                                next_day:
                                  id: 'http://jsonschema.net/rates/next_day'
                                  type: string
                                  name: next_day
                                two_day:
                                  id: 'http://jsonschema.net/rates/two_day'
                                  type: string
                                  name: two_day
                                ground:
                                  id: 'http://jsonschema.net/rates/ground'
                                  type: string
                                  name: ground
                              name: rates
                          required:
                            - company
                            - rates
                          title: xyz
                        variable: xyz_response.body
                        content: application/json
                      cek:
                        schema:
                          $schema: 'http://json-schema.org/draft-04/schema#'
                          id: 'http://jsonschema.net'
                          type: object
                          properties:
                            company:
                              id: 'http://jsonschema.net/company'
                              type: string
                              name: company
                            rates:
                              id: 'http://jsonschema.net/rates'
                              type: object
                              properties:
                                next_day:
                                  id: 'http://jsonschema.net/rates/next_day'
                                  type: string
                                  name: next_day
                                two_day:
                                  id: 'http://jsonschema.net/rates/two_day'
                                  type: string
                                  name: two_day
                                ground:
                                  id: 'http://jsonschema.net/rates/ground'
                                  type: string
                                  name: ground
                              name: rates
                          required:
                            - company
                            - rates
                          title: cek
                        variable: cek_response.body
                        content: application/json
                    outputs:
                      output:
                        schema:
                          $ref: '#/definitions/shipping'
                        variable: message.body
                        content: application/json
                    actions:
                      - set: output.xyz.next_day
                        from: xyz.rates.next_day
                      - set: output.xyz.two_day
                        from: xyz.rates.two_day
                      - set: output.xyz.ground
                        from: xyz.rates.ground
                      - set: output.cek.next_day
                        from: cek.rates.next_day
                      - set: output.cek.two_day
                        from: cek.rates.two_day
                      - set: output.cek.ground
                        from: cek.rates.ground
                    description: Map responses from invoke_xyz and invoke_cek to output
            - operations:
                - get.stores
              execute:
                - invoke:
                    title: invoke_google_geolocate
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    target-url: 'https://maps.googleapis.com/maps/api/geocode/json?&address={zip}'
                    output: google_geocode_response
                - gatewayscript:
                    title: gws-format-maps-link
                    source: >-
                      // Require API Connect Functions

                      var apic = require('local:///isp/policy/apim.custom.js');



                      // Save the Google Geocode response body to variable

                      var mapsApiRsp
                      = apic.getvariable('google_geocode_response.body');



                      // Get location attributes from geocode response body

                      var location = mapsApiRsp.results[0].geometry.location;



                      // Set up the response data object, concat the latitude and
                      longitude

                      var rspObj = {

                        "google_maps_link": "https://www.google.com/maps?q="
                      + location.lat + "," + location.lng

                      };



                      // Save the output

                      apic.setvariable('message.body', rspObj);
    catch: []
paths:
  /shipping:
    get:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/shipping'
      summary: Calculate shipping costs to a destination zip code
      operationId: shipping.calc
      parameters:
        - name: zip
          type: string
          required: true
          in: query
          description: Destination zip code.
  /stores:
    get:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/store_location'
      tags:
        - stores
      summary: Locate store near zip code
      operationId: get.stores
      parameters:
        - name: zip
          type: string
          required: true
          in: query
definitions:
  rates:
    properties:
      next_day:
        type: string
        example: '20.00'
      two_day:
        type: string
        example: '17.00'
      ground:
        type: string
        example: '8.00'
    required:
      - two_day
      - next_day
      - ground
  shipping:
    properties:
      xyz:
        type: string
        $ref: '#/definitions/rates'
      cek:
        type: string
        $ref: '#/definitions/rates'
    required:
      - xyz
      - cek
  store_location:
    properties:
      google_maps_link:
        type: string
        example: 'https://www.google.com/maps?q=34.1030032,-118.4104684'
    required:
      - google_maps_link
