#!/usr/bin/env bash

OPTIND=1         # Reset in case getopts has been used previously in the shell.

CORE_GIT_REPO="https://github.com/ibm-apiconnect/pot-onprem-core.git"
SVCS_GIT_REPO="https://github.com/ibm-apiconnect/pot-onprem-services.git"
CONS_GIT_REPO="https://github.com/ibm-apiconnect/pot-onprem-consumer.git"
GIT_BRANCH=""

show_help() {
  printf "\n"
  printf "Usage: clone -v VERSION"
  printf "\n"
  printf "Versions:     consult lab guide\n"
  printf "\n"
}

while getopts ":v:" opt; do
    case "$opt" in
    h)
      show_help
      exit 0
      ;;
    v)
      GIT_BRANCH=$OPTARG

      rm -rf ~/.pot/apic-pot

      git clone -b $GIT_BRANCH $CORE_GIT_REPO ~/.pot/core
      git clone -b $GIT_BRANCH $SVCS_GIT_REPO ~/.pot/services
      git clone -b $GIT_BRANCH $CONS_GIT_REPO ~/.pot/consumer

      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift