#!/usr/bin/env bash

# PRE-REQS
# Install Node 4.4.x using instructions at https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
# Include node install build tools: sudo apt-get install -y build-essential

# Set Variables
ihs_fn="ihs.tgz"
plugin_fn="plugin.tgz"
liberty_controller_fn="apiconnect-collective-controller-linux-x86_64-1.3.1.tgz"
download_dir="/home/student/Downloads/apic-liberty-packages"

# Download Packages...
sudo -u student mkdir $download_dir
cd $download_dir

printf "\nDownloading IHS Package...\n"
echo `swift download pot-collective-controller "$ihs_url"`

printf "\nDownloading IHS Plugin Package...\n"
echo `swift download pot-collective-controller "$plugin_url"`

printf "\nDownloading Liberty Controller Package...\n"
echo `swift download pot-collective-controller "$liberty_controller_url"`

echo `chown -R student:student "$download_dir"`

# Install Liberty Packages
printf "\nInstalling Liberty Controller Package, this may take a minute...\n"
echo `npm install -g --unsafe-perm "$download_dir/$liberty_controller_fn"`

printf "\nInstalling Liberty Member Package, this may take a minute...\n"
echo `npm install -g --unsafe-perm apiconnect-collective-member`

# Configure Liberty
printf "\nStarting Liberty Controller...\n"
sudo -u student wlpn-controller setup --password=Passw0rd!
sudo -u student wlpn-controller start

printf "\nConfiguring Liberty Collective...\n"
sleep 5
sudo -u student wlpn-collective updateHost xubuntu-vm --user=student --password=Passw0rd! --port=9443 --host=xubuntu-vm --rpcUser=student --rpcUserPassword=Passw0rd! --autoAcceptCertificates

# Install IHS
printf "\nInstalling IHS...\n"
mkdir -p /opt/IBM
cd /opt/IBM/
echo `tar xf "$download_dir/$ihs_fn"`
echo `tar xf "$download_dir/$plugin_fn"`

# Cleaning Files
printf "\nCleaning Files...\n"
rm -rf $download_dir

# Configure IHS
printf "\nConfiguring IHS...\n"
cd /home/student/.liberty/wlp/bin/
sudo -u student wlpn-controller ihsSetup --host=xubuntu-vm --port=9443 --user=student --password=Passw0rd! --keystorePassword=Passw0rd! --pluginInstallRoot="/opt/IBM/WebSphere/Plugins/" --webServerNames=webserver1

printf "\nCopying IHS Keys...\n"
sleep 5
cp plugin-cfg.xml /opt/IBM/WebSphere/Plugins/config/webserver1/
cp plugin-key.jks /opt/IBM/WebSphere/Plugins/config/webserver1/

printf "\nRegistering IHS with Liberty...\n"
sudo -u student wlpn-controller ihsRegister --host=xubuntu-vm --port=9443 --user=student --password=Passw0rd! --ihsIp=xubuntu-vm --ihsPort=80

printf "\nConverting IHS Keys...\n"
cd /opt/IBM/HTTPServer/bin/
rm /opt/IBM/WebSphere/Plugins/config/webserver1/plugin-key.kdb
./gskcmd -keydb -convert -pw Passw0rd! -db /opt/IBM/WebSphere/Plugins/config/webserver1/plugin-key.jks -old_format jks -target /opt/IBM/WebSphere/Plugins/config/webserver1/plugin-key.kdb -new_format cms -stash
sleep 5
./gskcmd -cert -setdefault -pw Passw0rd! -db /opt/IBM/WebSphere/Plugins/config/webserver1/plugin-key.kdb -label default
sleep 5

# Start IBM HTTP Server
printf "\nStarting IHS...\n"
/opt/IBM/HTTPServer/bin/apachectl -k start

printf "\nSetup Complete!\n"