#!/usr/bin/env bash

OPTIND=1         # Reset in case getopts has been used previously in the shell.

POTDIR=~/.pot
CONS_GIT_REPO="https://github.com/ibm-apiconnect/pot-consumer.git"
GIT_BRANCH=""


printf "Please be patient, this will take a while.\n"
printf "If prompted for a password, ignore the message and continue to wait.\n"
printf "\n"


consumer() {

  # Stop & unregister server
  echo Passw0rd! | sudo -S stop pot-consumer
  echo Passw0rd! | sudo -S forever-service delete pot-consumer

  # Remove old source files
  rm -rf ~/consumer $POTDIR/consumer

  # Re-clone new package
  git clone -b $GIT_BRANCH $CONS_GIT_REPO $POTDIR/consumer

  # Copy source to new location
  cp -r ~/.pot/consumer ~/consumer

  # Install new source
  cd ~/consumer
  npm install --silent

  # Register start server
  echo Passw0rd! | sudo -S forever-service install -s bin/www pot-consumer
  echo Passw0rd! | sudo -S start pot-consumer

}

while getopts ":v:" opt; do
    case "$opt" in
    v)
      GIT_BRANCH=$OPTARG
      consumer
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift