#!/usr/bin/env bash

# stop pot-consumer, uninstall, re-install, re-start

echo Passw0rd! | sudo -S stop pot-consumer
echo Passw0rd! | sudo -S forever-service delete pot-consumer
rm -rf ~/consumer
cp -r ~/.pot/consumer ~/consumer
cd ~/consumer
npm install
echo Passw0rd! | sudo -S forever-service install -s bin/www pot-consumer
echo Passw0rd! | sudo -S start pot-consumer