#!/usr/bin/env bash

PATCHSCRIPTS=~/.pot/core/env-setup/patch-scripts
log="/tmp/update-pot.log"

if [ "$(ls -A $PATCHSCRIPTS)" ]
  then
    chmod 775 "${PATCHSCRIPTS}/"*
fi

for SCRIPT in "${PATCHSCRIPTS}/"*
  do
    case "${SCRIPT}" in
      *~|*.bak)
        continue
        ;;
      *)
        if [ -f "${SCRIPT}" -a -x "${SCRIPT}" ]; then
          printf "Starting Script:${SCRIPT}\n"
          printf "\n"
          "${SCRIPT}" $@ >> "$log"
          if [ $? -ne 0 ]; then
            printf "ERROR with ${SCRIPT}\n"
            printf "\n"
          fi
        fi
        ;;
    esac
done