#!/usr/bin/env bash

PATCHSCRIPTS=~/.pot/core/env-setup/patch-scripts
log="/tmp/update-pot.log"

if [ "$(ls -A $PATCHSCRIPTS)" ]
  then
    chmod 775 "${PATCHSCRIPTS}/"*
fi

for SCRIPT in "${PATCHSCRIPTS}/"*
  do
    case "${SCRIPT}" in
      *~|*.bak)
        continue
        ;;
      *)
        if [ -f "${SCRIPT}" -a -x "${SCRIPT}" ]; then
          printf "Found/Starting Script:${SCRIPT}\n";
          "${SCRIPT}" $@ >> "$log"
          #echo $?;
          if [ $? -ne 0 ]; then
            echo "ERROR with ${SCRIPT}";
            #break;
          fi
        fi
        ;;
    esac
done