#!/usr/bin/env bash

# stop pot-services, uninstall, re-install, re-start

echo Passw0rd! | sudo -S stop pot-services
echo Passw0rd! | sudo -S forever-service delete pot-services
rm -rf ~/services
cp -r ~/.pot/services ~/services
cd ~/services
npm install
echo Passw0rd! | sudo -S forever-service install -s bin/www pot-services
echo Passw0rd! | sudo -S start pot-services