#!/usr/bin/env bash

# PRE-REQS
# Install Node 4.4.x using instructions at https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
# Include node install build tools: sudo apt-get install -y build-essential

# Set Variables
# Target version for 5010 controller:  2.3.0
# Target version for 5010 member:  1.3.5
collective_controller_fn="apiconnect-collective-controller-linux-x86_64-2.3.0.tgz"
ihs_fn="ihs.tgz"
plugin_fn="plugin.tgz"
download_dir="/home/student/Downloads/apic-collective-packages"

# Download Packages...
mkdir $download_dir
cd $download_dir

printf "\nDownloading IHS Package...\n"
echo `swift download pot-collective-controller "$ihs_fn"`

printf "\nDownloading IHS Plugin Package...\n"
echo `swift download pot-collective-controller "$plugin_fn"`

printf "\nDownloading Collective Controller Package...\n"
echo `swift download pot-collective-controller "$collective_controller_fn"`

# Install Collective Packages
printf "\nInstalling Collective Controller Package, this may take a minute...\n"
echo Passw0rd! | sudo -S npm install -g --unsafe-perm $download_dir/$collective_controller_fn

printf "\nInstalling Collective Member Package, this may take a minute...\n"
echo Passw0rd! | sudo -S npm install -g --unsafe-perm apiconnect-collective-member@1.1.1

# Configure Collective
printf "\nStarting Collective Controller...\n"
wlpn-controller setup --password=Passw0rd!
wlpn-controller start

printf "\nConfiguring Collective Collective...\n"
sleep 5
echo Passw0rd! | sudo -S wlpn-collective updateHost xubuntu-vm --user=student --password=Passw0rd! --port=9443 --host=xubuntu-vm --rpcUser=student --rpcUserPassword=Passw0rd! --autoAcceptCertificates

# Install IHS
printf "\nInstalling IHS...\n"
echo Passw0rd! | sudo -S mkdir -p /opt/IBM
cd /opt/IBM/
echo Passw0rd! | sudo -S tar xf $download_dir/$ihs_fn
echo Passw0rd! | sudo -S tar xf $download_dir/$plugin_fn

# Cleaning Files
printf "\nCleaning Files...\n"
rm -rf $download_dir

# Configure IHS
printf "\nConfiguring IHS...\n"
cd /home/student/.liberty/wlp/bin/
wlpn-controller ihsSetup --host=xubuntu-vm --port=9443 --user=student --password=Passw0rd! --keystorePassword=Passw0rd! --pluginInstallRoot="/opt/IBM/WebSphere/Plugins/" --webServerNames=webserver1

printf "\nCopying IHS Keys...\n"
sleep 5
echo Passw0rd! | sudo -S cp plugin-cfg.xml /opt/IBM/WebSphere/Plugins/config/webserver1/
echo Passw0rd! | sudo -S cp plugin-key.jks /opt/IBM/WebSphere/Plugins/config/webserver1/

printf "\nRegistering IHS with Collective...\n"
wlpn-controller ihsRegister --host=xubuntu-vm --port=9443 --user=student --password=Passw0rd! --ihsIp=xubuntu-vm --ihsPort=80

printf "\nConverting IHS Keys...\n"
cd /opt/IBM/HTTPServer/bin/
echo Passw0rd! | sudo -S rm /opt/IBM/WebSphere/Plugins/config/webserver1/plugin-key.kdb
echo Passw0rd! | sudo -S ./gskcmd -keydb -convert -pw Passw0rd! -db /opt/IBM/WebSphere/Plugins/config/webserver1/plugin-key.jks -old_format jks -target /opt/IBM/WebSphere/Plugins/config/webserver1/plugin-key.kdb -new_format cms -stash
sleep 5
echo Passw0rd! | sudo -S ./gskcmd -cert -setdefault -pw Passw0rd! -db /opt/IBM/WebSphere/Plugins/config/webserver1/plugin-key.kdb -label default
sleep 5

# Start IBM HTTP Server
printf "\nStarting IHS...\n"
echo Passw0rd! | sudo -S /opt/IBM/HTTPServer/bin/apachectl -k start

printf "\nSetup Complete!\n"