#!/bin/sh

# Version: 5010
# Version Fix: Rework for 5010, add support for PoT version branch

OPTIND=1         # Reset in case getopts has been used previously in the shell.

POTDIR=~/.pot
SCRIPTDIR=~/.pot/core/env-setup/update-scripts
CORE_GIT_REPO="https://github.com/ibm-apiconnect/pot-onprem-core.git"
SVCS_GIT_REPO="https://github.com/ibm-apiconnect/pot-onprem-services.git"
CONS_GIT_REPO="https://github.com/ibm-apiconnect/pot-onprem-consumer.git"
GIT_BRANCH=""

#now=$(date +"%m_%d_%Y")
#log="/tmp/update-pot.log"
#echo "Starting update-pot: Logging to $log..."
#date | tee -a "$log"

#if [ ! -d "$POTDIR" ]
#then
#  mkdir /home/student/.pot
#fi

clone() {
  cd ~/.pot
  rm -rf apic-pot/
  git clone -b $GIT_BRANCH $CORE_GIT_REPO core
  git clone -b $GIT_BRANCH $SVCS_GIT_REPO services
  git clone -b $GIT_BRANCH $CONS_GIT_REPO consumer
}

patch() {
  if [ "$(ls -A $SCRIPTDIR)" ]
    then
      chmod 775 "${SCRIPTDIR}/"*
  fi

  for SCRIPT in "${SCRIPTDIR}/"*
    do
      case "${SCRIPT}" in
        *~|*.bak)
          continue
          ;;
        *)
          if [ -f "${SCRIPT}" -a -x "${SCRIPT}" ]; then
            echo "Found/Starting Script:${SCRIPT}";
            "${SCRIPT}" $@ >> "$log"
	          #echo $?;
            if [ $? -ne 0 ]; then
              echo "ERROR with ${SCRIPT}";
		          #break;
	          fi
          fi
          ;;
      esac
    done
}

labs () {
	rm -rf ~/lab_files
	cp -R $POTDIR/core/lab-files ~/lab_files
	rm -rf ~/lab_files/.git
	rm -rf ~/lab_files/.gitignore
	rm -rf ~/lab_files/LICENSE
	rm -rf ~/lab_files/README.md
}

services () {
  echo "services go here"
}

show_help() {
  printf "\n"
  printf "Usage: update-pot -v VERSION -c COMMAND \n"
  printf "\n"
  printf "Versions:     consult lab guide\n"
  printf "\n"
  printf "Commands:\n"
  printf "   clone      does a full clone of the GIT repo to ~/.pot\n"
  printf "   patch      clones GIT repo and runs all scripts found in ~/.pot/apic-pot/env-setup/patch-scripts\n"
  printf "   labs       clones GIT and installs and configures lab files\n"
  printf "   services   clones GIT and installs and configures stub services\n"
  printf "   all        performs a clone, patch, labs and services in sequence\n"
  printf "\n"
}

while getopts ":hc:v:" opt; do
    case "$opt" in
    h)
      show_help
      exit 0
      ;;
    v)
      GIT_BRANCH=$OPTARG
      ;;
    c)
      case "$OPTARG" in
        clone)
          clone | tee -a "$log"
          ;;
        patch)
          clone | tee -a "$log"
          patch | tee -a "$log"
          ;;
        labs)
          clone | tee -a "$log"
          labs  | tee -a "$log"
          ;;
        services)
          clone | tee -a "$log"
          services  | tee -a "$log"
          ;;
        all)
          clone | tee -a "$log"
          patch | tee -a "$log"
          labs  | tee -a "$log"
          services  | tee -a "$log"
          ;;
      esac
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift