#!/bin/sh

# Version: 5010
# Version Fix: Rework for 5010, add support for PoT version branch

OPTIND=1         # Reset in case getopts has been used previously in the shell.

POTDIR=~/.pot
SCRIPTDIR=~/.pot/core/env-setup/update-scripts
CORE_GIT_REPO="https://github.com/ibm-apiconnect/pot-onprem-core.git"
GIT_BRANCH=""
now=$(date +"%m_%d_%Y")
log="/tmp/update-pot.log"

clear
printf "\n"
printf "Please be patient, this may take a while.\n"
printf "If prompted for a password, ignore the message and continue to wait.\n"
printf "\n"
sleep 3

if [ ! -d "$POTDIR" ]
then
  mkdir $POTDIR
fi

show_help() {
  printf "\n"
  printf "Usage:                update-pot -v VERSION [-c COMMAND] \n"
  printf "\n"
  printf "Versions:             consult lab guide for version number\n"
  printf "\n"
  printf "Commands:\n"
  printf "   patch              runs all scripts found in ~/.pot/apic-pot/env-setup/patch-scripts\n"
  printf "   labs               installs and configures lab files\n"
  printf "   consumer           clones the consumer GIT repository and installs and runs the consumer app\n"
  printf "   services           clones the services GIT repository and installs and runs the stub services\n"
  printf "   toolkit            installs the apic developer toolkit\n"
  printf "   clean-collective   uninstalls and removes collective - FORCES RESTART\n"
  printf "   setup-collective   updates the collective for the current version - MUST USE clean-collective FIRST\n"
  printf "\n"
}

clone() {
  printf "\n"
  printf "Starting update-pot: Logging to $log...\n"
  printf "\n"
  date | tee -a "$log"

  rm -rf $POTDIR/*

  git clone -b $GIT_BRANCH $CORE_GIT_REPO $POTDIR/core

  chmod 775 $POTDIR/core/env-setup/patch-scripts/*
  chmod 775 $POTDIR/core/env-setup/system-scripts/*
  chmod 775 $POTDIR/core/env-setup/update-scripts/*
}

while getopts ":hc:v:" opt; do
    case "$opt" in
    h)
      show_help
      exit 0
      ;;
    v)
      GIT_BRANCH=$OPTARG
      clone | tee -a "$log"
      ;;
    c)
      case "$OPTARG" in
        patch)
          echo `$SCRIPTDIR/patch` | tee -a "$log"
          ;;
        labs)
          echo `$SCRIPTDIR/labs` | tee -a "$log"
          ;;
        consumer)
          echo `$SCRIPTDIR/consumer -v $GIT_BRANCH` | tee -a "$log"
          ;;
        services)
          echo `$SCRIPTDIR/services -v $GIT_BRANCH` | tee -a "$log"
          ;;
        toolkit)
          echo `$SCRIPTDIR/toolkit` | tee -a "$log"
          ;;
        clean-collective)
          echo `$SCRIPTDIR/clean-collective` | tee -a "$log"
          ;;
        setup-collective)
          echo `$SCRIPTDIR/setup-collective` | tee -a "$log"
          ;;
      esac
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift