#!/usr/bin/env bash

complete_dir=~/lab_files/lab$1/complete/inventory/
student_dir=~/ThinkIBM/inventory/
files=()
lab_num=$1

validate_lab2(){
  files=(common/models/item.json common/models/review.json definitions/inventory.yaml server/datasources.json server/model-config.json)
  run_diff
}

validate_lab3(){
  files=(common/models/item.js server/config.json)
  run_diff
}

validate_lab4(){
  files=(definitions/inventory.yaml definitions/oauth_1.0.0.yaml)
  run_diff
}

validate_lab5(){
  files=(definitions/inventory.yaml definitions/oauth_1.0.0.yaml definitions/financing_1.0.0.yaml definitions/logistics_1.0.0.yaml)
  run_diff
}

validate_lab6(){
  files=(definitions/inventory.yaml definitions/oauth_1.0.0.yaml definitions/financing_1.0.0.yaml definitions/logistics_1.0.0.yaml definitions/inventory-product.yaml)
  run_diff
}

run_diff(){
  for i in "${files[@]}"
  do
    printf "Running validation check on file: %s \n" "$i"
    if [[ $lab_num -gt 3 && $i = "definitions/inventory.yaml" ]]
      then
        printf "maintaining your app-id\n"
        student_appid=`grep "app-id: " $student_dir$i | cut -c16-`
        old_appid=`grep "app-id: " $complete_dir$i | cut -c16-`
        echo `sed -i s/$old_appid/$student_appid/ $complete_dir$i`
    fi
    result=$(diff $student_dir$i $complete_dir$i)
    if [ $? -eq 0 ]
      then
        printf "... Looks good!"
      else
        printf "$result"
    fi
    printf "\n\n"
  done
}

case "$1" in
  2)
    validate_lab2
    ;;
  3)
    validate_lab3
    ;;
  4)
    validate_lab4
    ;;
  5)
    validate_lab5
    ;;
  6)
    validate_lab6
    ;;
  *)
    echo "Usage: validate_lab {2|3|4|5|6}"
    exit 1
    ;;
esac
